services:
    web:
        image: "iot-devices-management"
        build: .
        ports:
            - "8000:8080"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
             SA_PASSWORD: "iot_devices"
             ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"